[project]
name = "cluster-toy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
    "numpy>=2.3.1",
    "python-magic>=0.4.27",
    "scikit-learn>=1.7.0",
]
